// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE92Vj6wEiW8cm-juY_19Pi14NHhE5gxQ',
    appId: '1:334518941986:web:f10f46637e9d4050b5cd7b',
    messagingSenderId: '334518941986',
    projectId: 'tmbeira-addd0',
    authDomain: 'tmbeira-addd0.firebaseapp.com',
    storageBucket: 'tmbeira-addd0.appspot.com',
    measurementId: 'G-SNH7LBRSH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2FbuVqJUeRcaMCFvA-N6PlqWr897yY0',
    appId: '1:334518941986:android:4ab36bba31d43a7db5cd7b',
    messagingSenderId: '334518941986',
    projectId: 'tmbeira-addd0',
    storageBucket: 'tmbeira-addd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYG11xPXws6-rkSFBMnHkbDk-4cGDZN88',
    appId: '1:334518941986:ios:9ae6f5234022ff62b5cd7b',
    messagingSenderId: '334518941986',
    projectId: 'tmbeira-addd0',
    storageBucket: 'tmbeira-addd0.appspot.com',
    iosBundleId: 'com.example.cobradortpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYG11xPXws6-rkSFBMnHkbDk-4cGDZN88',
    appId: '1:334518941986:ios:9ae6f5234022ff62b5cd7b',
    messagingSenderId: '334518941986',
    projectId: 'tmbeira-addd0',
    storageBucket: 'tmbeira-addd0.appspot.com',
    iosBundleId: 'com.example.cobradortpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE92Vj6wEiW8cm-juY_19Pi14NHhE5gxQ',
    appId: '1:334518941986:web:c533ebc8dffeddccb5cd7b',
    messagingSenderId: '334518941986',
    projectId: 'tmbeira-addd0',
    authDomain: 'tmbeira-addd0.firebaseapp.com',
    storageBucket: 'tmbeira-addd0.appspot.com',
    measurementId: 'G-0NJDXXGM4S',
  );
}
